spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lint_shop?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
eureka:
  client:
    service-url:
      defaultZone: http://106.14.167.55:8761/eureka/
